### ISSUE TITLE
Props destruct documentation doest work for some code

### ISSUE THREAD

**Issue by s-u-d-o-e-r** [kkoomen/vim-doge#110]
Try to generate doc for this code, it doesn’t  work, but if you remove "true &&" or className it will work

```
const Test = ({ someVal }) => {
	return <div>{true && someVal ? <small className="helper-text">{someVal}</small> : null}</div>;
};
export default Test;
```

![image](https://user-images.githubusercontent.com/29402490/96246078-cd6c0000-0fb0-11eb-9b49-de008a4f46c2.png)

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v3.2.7](https://github.com/kkoomen/vim-doge/tree/v3.2.7).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v3.2.8](https://github.com/kkoomen/vim-doge/tree/v3.2.8).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v3.2.9](https://github.com/kkoomen/vim-doge/tree/v3.2.9).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by s-u-d-o-e-r** [comment]
@kkoomen I have updated the version but it still doesn’t  work even if I run npm build manually, no output, nothing

**Comment by kkoomen** [comment]
Apologies. I noticed I can simply use the TSX parser which supports seems to support TSX/JSX and every other syntastic sugar in JS/TS. This bug has been fixed and released in [v3.2.10](https://github.com/kkoomen/vim-doge/tree/v3.2.10).
